apiVersion: kubeadm.k8s.io/v1beta3
caCertPath: /etc/kubernetes/pki/ca.crt
discovery:
  bootstrapToken:
    apiServerEndpoint: 10.0.1.125:6443
    caCertHashes:
    - sha256:591edc9fa3ea3b239d84160662978a8947a016b29145b37b113f0c68f2b72273
    token: dswmbu.oauz1n8y2ojnqi0e
  timeout: 5m0s
  tlsBootstrapToken: dswmbu.oauz1n8y2ojnqi0e
kind: JoinConfiguration
nodeRegistration:
  criSocket: unix:///var/run/containerd/containerd.sock
  imagePullPolicy: IfNotPresent
  kubeletExtraArgs:
    cloud-provider: aws
  name: ip-10-0-11-4.ec2.internal
  taints: null

